SimulationRobobo: add realtime option, add puck_position().
ci-group/learning_machines_robobo pull request #10
Opened 2023-01-28 11:26 UTC by dangbert

* Adds option to SimulationRobobo for speeding up simulator.

* Implements puck_position() so student can easily read the location of the red block for task3.

* Clarifies the purpose of some functions by adding comments.

Example usage:

````python
rob =  SimulationRobobo(number=number).connect(
    address="127.0.0.1", port=19997, realtime=realtime
)

cur_pos = rob.puck_position()
base_pos = rob.base_position()
detected = rob.base_detects_food()
assert cur_pos is not None and base_pos is not None
print(f"cur_pos = {cur_pos}")
print(f"base_pos = {base_pos}")
print(f"detected = {detected}")
dist = math.sqrt(
    (cur_pos[0] - base_pos[0]) ** 2 + (cur_pos[1] - base_pos[1]) ** 2
)
print(f"dist = {dist:.3f}")
````

Example output:
![image](https://user-images.githubusercontent.com/6439020/215263916-5e708d26-ab5b-4f19-a974-e68f3710aa2e.png)

2023-02-07 09:51 UTC, portaloffreedom requested changes

2023-02-07 09:51 UTC, portaloffreedom commented on src/robobo/simulation.py
> +                vrep.simxSetBooleanParameter(
could you wrap this function in `vrep.unwrap_vrep` ? so that if it returns an error and fails to set real time, students will know?

2023-02-07 09:51 UTC, portaloffreedom commented on src/robobo/simulation.py
> +            "Food".format(self._value_number), vrep.simx_opmode_blocking
what is this format suppose to do? As far as I can tell it's changing nothing here (I'm surprised it doesn't give out errors)

2024-01-07 19:53 UTC, JJWRoeloffs commented
Closing this pull request, as it is no longer relevant with the rewrite.

Realtime option exists for this rewrite, puck position might be added at some point, but the implementation provided in this branch is substandard, as it doesn't give a sensible error message when running the code in the food collection scene.

2024-01-07 19:53 UTC, closed without merging